---
- hosts: all
  user: AbdullahTaher
 
  vars:
    project_path: /home/Abdullah/myproject
  tasks:
    - name: Crear directorio
     
      file:
        dest={{ project_path }}
        mode=0755
        recurse=yes
        state=directory
    - name: Clonar el repositorio
      git:
        repo: https://github.com/AbdullahTaher93/CCMYproject.git
        dest: "{{ project_path }}"
    - name: Instalar npm
      become: true
      become_method: sudo
      apt:
        pkg=npm state=present
    
    - name: Instala dependecias npm
      npm:
        path={{ project_path }}
    - name: Instala pm2
      become: true
      become_method: sudo
      npm:
        name: pm2
        global: yes
    - name: Elimina el proceso lanzado anteriormente
      command: pm2 delete PR
      ignore_errors: yes
    - name: Redirigir puertos
      become: true
      become_method: sudo
      command: iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
    - name: Arrancar pm2
      command: pm2 start {{ project_path }}/index.js --name PR
    - name: Borrar directorio
      file:
        state: absent
        path: "{{ project_path }}"
