---
- hosts: all
  user: AbdullahTaher
  Host_pass: AbdullahTaher112233
  
  vars:
    - project_path: /home/AbdullahTaher/projects
    - install_pack: ["nodejs","npm","git"]
  tasks:
  - name: install "{{ install_pack }}"
      become: yes
      become_user: root
      apt:
        name: "{{ install_pack }}"
        state: present

    - name: Create project location
      become_method: sudo
      file:
        path: "{{ project_path }}"
        state: directory

    - name: clone RP
      git:
        repo: https://github.com/AbdullahTaher93/CCMYproject.git
        dest: "{{ project_path }}"
    

    name: Install dependencies
      npm:
        path: "{{ project_path }}"

    - name: Install pm2
      become: yes
      become_user: root
      command: npm install pm2 -g



    - name: Redirect ports
      become: true
      become_method: sudo
      command: iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
    - name: Start pm2
      command: pm2 start {{ project_path }}/index.js --name PR
    - name: Delete directory
      file:
        state: absent
        path: "{{ project_path }}"
