---
- hosts: all
  user: AbdullahTaher
  vars:
    project_path: /home/AbdullahTaher/project
  tasks:
    
    - name: clone RP
      git:
        repo: https://github.com/AbdullahTaher93/CCMYproject.git
        dest: "{{ project_path }}"
    - name: install npm
      become: true
      become_method: sudo
      apt:
        pkg=npm state=present
    
   
    - name: Install dependencies npm
      npm:
        path={{ project_path }}
    - name: Install pm2
      become: true
      become_method: sudo
      npm:
        name: pm2
        global: yes
    - name: Remove the previously released process
      command: pm2 delete PR
      ignore_errors: yes
    - name: Redirect ports
      become: true
      become_method: sudo
      command: iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
    - name: Start pm2
      command: pm2 start {{ project_path }}/app.js --name PR
    - name: Delete directory
      file:
        state: absent
        path: "{{ project_path }}"
